### ISSUE TITLE
Broken build

### ISSUE THREAD

**Issue by hfiguiere** [flathub/dev.goats.xivlauncher#17]
The build is broken on master.

It tries to use a non existant runtime.

Submitting change through PR and waiting for the build allow avoiding that kind of situation.

**Comment by orowith2os** [comment]
Dotnet builds have been weird for me for a while too, related to my MR to Flathub regarding OpenUTAU.

**Comment by goaaats** [comment]
We got some more folks that will pay closer attention to Linux releases and fixed the build with https://github.com/flathub/dev.goats.xivlauncher/commit/ae2a7bbe32bb76bbe8c7dfce4af25a138edfbffa, apologies. It's hard to keep .NET apps building without making regular releases, since the CDN URLs for packages seem to change.
